apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: analytics-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SEU_USUARIO/fase3-argocd.git
    targetRevision: main
    path: services/analytics-service
  destination:
    server: https://kubernetes.default.svc
    namespace: analytics-service
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
