apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flag-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SEU_USUARIO/fase3-argocd.git
    targetRevision: main
    path: services/flag-service
  destination:
    server: https://kubernetes.default.svc
    namespace: flag-service
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
