apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: analytics-service-hpa
  namespace: analytics-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analytics-service-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 5
